[build]
builder = "nixpacks"
buildCommand = "cd edfest-browser && npm install && npm run build"

[deploy]
startCommand = "cd edfest-browser && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
