[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_22"]

[deploy]
startCommand = "node scripts/seed.mjs && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
